---
- name: install essential packages (this may take a while)
  package: name="{{ item }}"
  with_items:
  - build-essential
  - debian-installer-launcher
  - git
  - gstreamer1.0-vaapi
  - i965-va-driver
  - libelf-dev
  - libncurses5-dev
  - libssl-dev
  - live-boot
  - lm-sensors
  - mesa-utils
  - pulseaudio
  - thermald
  - tlp
  - unionfs-fuse
  - va-driver-all
  - vainfo
  - dconf-editor
  - dconf-cli
  - x11-xserver-utils
  notify:
  - enable thermal services
  tags:
  - packages

- name: check if running in chroot (iso creation)
  shell: |
    if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then
      echo "chroot"
    fi
  register: chroot
  changed_when: False
  tags:
  - packages

- name: install intel-microcode (iso creation = no)
  package: name=intel-microcode
  when: chroot.stdout.find('chroot') == -1
  tags:
  - packages

- name: remove intel-microcode (iso creation = yes)
  package:
    name: intel-microcode
    state: absent
  when: chroot.stdout.find('chroot') != -1
  tags:
  - packages
 

